// ============================================
// UMADE - Multi-Language System (EN + Tamil)
// ============================================

const translations = {
    en: {
        // Navigation
        'nav.home': 'Home',
        'nav.shop': 'Shop',
        'nav.categories': 'Categories',
        'nav.about': 'About',
        'nav.contact': 'Contact',
        'nav.search_placeholder': 'Search organic products...',

        // Hero
        'hero.badge': '100% Organic & Fresh',
        'hero.title_1': 'Farm to Table,',
        'hero.title_2': 'Delivered to Your Door',
        'hero.subtitle': 'Discover the freshest organic fruits, vegetables, and groceries sourced directly from local farms. Healthy living starts with what you eat.',
        'hero.stat_farms': 'Partner Farms',
        'hero.stat_products': 'Organic Products',
        'hero.stat_delivery': 'Fast Delivery',

        // Features
        'features.free_delivery': 'Free Delivery',
        'features.fast_delivery_desc': 'Express shipping',
        'features.certified': 'Certified Organic',
        'features.returns': 'Easy Returns',
        'features.returns_desc': '30-day guarantee',

        // Categories
        'categories.tag': 'Browse by Category',
        'categories.title': 'Shop Our Organic Collection',
        'categories.subtitle': 'From farm-fresh produce to pantry essentials, we have everything you need for a healthy lifestyle.',
        'categories.fruits': 'Fresh Fruits',
        'categories.vegetables': 'Vegetables',
        'categories.dairy': 'Dairy & Eggs',
        'categories.bakery': 'Bakery',
        'categories.beverages': 'Beverages',
        'categories.pantry': 'Pantry',

        // Products
        'products.tag': 'Popular Products',
        'products.title': 'Fresh from the Farm',
        'products.subtitle': 'Handpicked organic produce delivered fresh to your doorstep.',
        'products.all': 'All',

        // How it works
        'how_it_works.tag': 'How It Works',
        'how_it_works.title': 'Fresh Organic Food in 3 Easy Steps',
        'how_it_works.step1_title': 'Choose Products',
        'how_it_works.step1_desc': 'Browse our wide selection of organic fruits, vegetables, and groceries.',
        'how_it_works.step2_title': 'Place Your Order',
        'how_it_works.step2_desc': 'Add items to your cart and checkout securely with multiple payment options.',
        'how_it_works.step3_title': 'Fast Delivery',
        'how_it_works.step3_desc': 'Receive your fresh organic groceries at your doorstep within 30 minutes.',

        // Testimonials
        'testimonials.tag': 'Testimonials',
        'testimonials.title': 'What Our Customers Say',

        // Newsletter
        'newsletter.title': 'Subscribe to Our Newsletter',
        'newsletter.subtitle': 'Get exclusive deals, recipes, and health tips delivered to your inbox. Plus, get 15% off your first order!',
        'newsletter.placeholder': 'Enter your email address',
        'newsletter.subscribe': 'Subscribe',

        // Footer
        'footer.description': 'Bringing the freshest organic produce from local farms to your table. Healthy eating made easy and convenient.',
        'footer.categories': 'Categories',
        'footer.quick_links': 'Quick Access',
        'footer.contact_us': 'Contact Us',
        'footer.phone': '+91 7200558060 / +91 9994014301',
        'footer.email': 'hello@umade.com',
        'footer.hours': 'Mon - Sun: 7:00 AM - 10:00 PM',
        'footer.copyright': 'All rights reserved. Made with love for healthy living.',
        'footer.privacy': 'Privacy Policy',
        'footer.terms': 'Terms of Service',
        'footer.cookies': 'Cookie Policy',

        // Cart
        'cart.title': 'Your Cart',
        'cart.total': 'Total:',
        'cart.checkout': 'Checkout',
        'cart.clear': 'Clear Cart',

        // Login
        'login.sign_in': 'Sign In',
        'login.welcome_back': 'Welcome back! Please enter your details.',
        'login.email': 'Email Address',
        'login.password': 'Password',
        'login.remember': 'Remember me',
        'login.forgot': 'Forgot password?',
        'login.or_continue': 'Or continue with',
        'login.google': 'Google',
        'login.apple': 'Apple',
        'login.no_account': "Don't have an account?",
        'login.sign_up': 'Sign up',
        'login.first_name': 'First Name',
        'login.last_name': 'Last Name',
        'login.phone': 'Phone Number',
        'login.confirm_password': 'Confirm Password',
        'login.agree': 'I agree to the Terms and Privacy Policy',
        'login.create_account': 'Create Account',
        'login.have_account': 'Already have an account?',
        'login.reset': 'Reset Password',
        'login.reset_desc': "Enter your email and we'll send you a reset link.",
        'login.send_link': 'Send Reset Link',

        // Tracking
        'tracking.live_tracking': 'Live Order Tracking',
        'tracking.title': 'Your Order is On the Way',
        'tracking.subtitle': 'Track your organic groceries in real-time from our farm to your doorstep.',
        'tracking.order_number': 'Order Number',
        'tracking.order_date': 'Order Date',
        'tracking.items': 'Items',
        'tracking.total': 'Total',
        'tracking.live': 'Live',
        'tracking.distance': 'away',
        'tracking.time': 'min',
        'tracking.speed': 'km/h',
        'tracking.call': 'Call',
        'tracking.message': 'Message',
        'tracking.progress': 'Delivery Progress',
        'tracking.placed': 'Order Placed',
        'tracking.preparing': 'Preparing',
        'tracking.out_delivery': 'Out for Delivery',
        'tracking.on_way': 'On the Way',
        'tracking.arriving': 'Arriving in',
        'tracking.delivered': 'Delivered',
        'tracking.estimated': 'Estimated',
        'tracking.order_items': 'Order Items',

        // Loyalty
        'loyalty.title': 'Umade Rewards',
        'loyalty.subtitle': 'Earn points on every purchase and redeem for discounts',
        'loyalty.points_balance': 'Points Balance',
        'loyalty.points_earned': 'Points Earned',
        'loyalty.points_redeemed': 'Points Redeemed',
        'loyalty.tier': 'Membership Tier',
        'loyalty.gold': 'Gold',
        'loyalty.how_to_earn': 'How to Earn Points',
        'loyalty.earn_rate': 'Earn 1 point per ₹10 spent',
        'loyalty.redeem_rate': '100 points = ₹50 discount',
        'loyalty.purchase_points': 'Purchase Points',
        'loyalty.purchase_desc': 'Earn 1 point for every ₹10 spent',
        'loyalty.review_points': 'Review Points',
        'loyalty.review_desc': 'Earn 50 points for each product review',
        'loyalty.refer_points': 'Referral Points',
        'loyalty.refer_desc': 'Earn 200 points for each successful referral',
        'loyalty.social_points': 'Social Points',
        'loyalty.social_desc': 'Earn 25 points for sharing on social media',
        'loyalty.redeem_title': 'Redeem Your Points',
        'loyalty.redeem_100': '₹50 Off',
        'loyalty.redeem_200': '₹125 Off',
        'loyalty.redeem_500': '₹350 Off',
        'loyalty.redeem_1000': '₹800 Off',
        'loyalty.history': 'Points History',
        'loyalty.date': 'Date',
        'loyalty.activity': 'Activity',
        'loyalty.points': 'Points',
        'loyalty.status': 'Status',

        // Referral
        'referral.title': 'Refer & Earn',
        'referral.subtitle': 'Share Umade with friends and earn rewards together',
        'referral.your_code': 'Your Referral Code',
        'referral.copy': 'Copy',
        'referral.share': 'Share via',
        'referral.whatsapp': 'WhatsApp',
        'referral.sms': 'SMS',
        'referral.email': 'Email',
        'referral.how_it_works': 'How It Works',
        'referral.step1': 'Share your unique referral code with friends',
        'referral.step2': 'Friends get ₹100 off their first order',
        'referral.step3': 'You earn ₹100 credit + 200 loyalty points',
        'referral.stats': 'Your Referral Stats',
        'referral.total_referrals': 'Total Referrals',
        'referral.successful': 'Successful',
        'referral.pending': 'Pending',
        'referral.earnings': 'Total Earnings',
        'referral.friends_title': 'Friends You've Referred',
        'referral.friend_name': 'Friend',
        'referral.order_value': 'Order Value',
        'referral.your_reward': 'Your Reward',
        'referral.referral_status': 'Status'
    },

    ta: {
        // Navigation
        'nav.home': 'முகப்பு',
        'nav.shop': 'கடை',
        'nav.categories': 'வகைகள்',
        'nav.about': 'எங்களைப் பற்றி',
        'nav.contact': 'தொடர்பு',
        'nav.search_placeholder': 'கரிம பொருட்களைத் தேடுங்கள்...',

        // Hero
        'hero.badge': '100% கரிம & புதியது',
        'hero.title_1': 'பண்ணை முதல் மேஜை வரை,',
        'hero.title_2': 'உங்கள் வீட்டிற்கு வழங்கப்படுகிறது',
        'hero.subtitle': 'உள்ளூர் பண்ணைகளில் இருந்து நேரடியாக பெறப்பட்ட புதிய கரிம பழங்கள், காய்கறிகள் மற்றும் மளிகைப் பொருட்களைக் கண்டறியுங்கள். ஆரோக்கியமான வாழ்க்கை நீங்கள் சாப்பிடுவதிலிருந்து தொடங்குகிறது.',
        'hero.stat_farms': 'கூட்டாளர் பண்ணைகள்',
        'hero.stat_products': 'கரிம பொருட்கள்',
        'hero.stat_delivery': 'விரைவான விநியோகம்',

        // Features
        'features.free_delivery': 'இலவச விநியோகம்',
        'features.fast_delivery_desc': 'விரைவு கப்பல்',
        'features.certified': 'சான்றளிக்கப்பட்ட கரிம',
        'features.returns': 'எளிதான வருவாய்',
        'features.returns_desc': '30-நாள் உத்தரவாதம்',

        // Categories
        'categories.tag': 'வகையினால் உலாவவும்',
        'categories.title': 'எங்கள் கரிம சேகரிப்பை வாங்குங்கள்',
        'categories.subtitle': 'பண்ணை-புதிய பொருட்களிலிருந்து மளிகை அத்தியாவசியங்கள் வரை, ஆரோக்கியமான வாழ்க்கைக்கு தேவையான அனைத்தும் எங்களிடம் உள்ளது.',
        'categories.fruits': 'புதிய பழங்கள்',
        'categories.vegetables': 'காய்கறிகள்',
        'categories.dairy': 'பால் பொருட்கள் & முட்டைகள்',
        'categories.bakery': 'பேக்கரி',
        'categories.beverages': 'பானங்கள்',
        'categories.pantry': 'மளிகை',

        // Products
        'products.tag': 'பிரபலமான பொருட்கள்',
        'products.title': 'பண்ணையிலிருந்து புதியது',
        'products.subtitle': 'உங்கள் வீட்டு வாசலுக்கு புதிய கரிம பொருட்களை வழங்கப்படுகிறது.',
        'products.all': 'அனைத்தும்',

        // How it works
        'how_it_works.tag': 'இது எப்படி வேலை செய்கிறது',
        'how_it_works.title': '3 எளிதான படிகளில் புதிய கரிம உணவு',
        'how_it_works.step1_title': 'பொருட்களைத் தேர்வு செய்யுங்கள்',
        'how_it_works.step1_desc': 'கரிம பழங்கள், காய்கறிகள் மற்றும் மளிகைப் பொருட்களின் பரந்த தேர்வை உலாவுங்கள்.',
        'how_it_works.step2_title': 'உங்கள் ஆர்டரை வைக்கவும்',
        'how_it_works.step2_desc': 'பல பணம் செலுத்தும் விருப்பங்களுடன் பாதுகாப்பாக சரிபார்க்க உங்கள் வண்டியில் பொருட்களைச் சேர்க்கவும்.',
        'how_it_works.step3_title': 'விரைவான விநியோகம்',
        'how_it_works.step3_desc': '30 நிமிடங்களுக்குள் உங்கள் வீட்டு வாசலில் புதிய கரிம மளிகைப் பொருட்களைப் பெறுங்கள்.',

        // Testimonials
        'testimonials.tag': 'வாடிக்கையாளர் கருத்துகள்',
        'testimonials.title': 'எங்கள் வாடிக்கையாளர்கள் என்ன கூறுகிறார்கள்',

        // Newsletter
        'newsletter.title': 'எங்கள் செய்திமடலுக்கு பதிவு செய்யுங்கள்',
        'newsletter.subtitle': 'பிரத்தியேக சலுகைகள், சமையல் குறிப்புகள் மற்றும் ஆரோக்கிய குறிப்புகளை உங்கள் இன்பாக்ஸில் பெறுங்கள். மேலும், உங்கள் முதல் ஆர்டரில் 15% தள்ளுபடி பெறுங்கள்!',
        'newsletter.placeholder': 'உங்கள் மின்னஞ்சல் முகவரியை உள்ளிடவும்',
        'newsletter.subscribe': 'பதிவு செய்யுங்கள்',

        // Footer
        'footer.description': 'உள்ளூர் பண்ணைகளில் இருந்து உங்கள் மேஜைக்கு புதிய கரிம பொருட்களைக் கொண்டு வருகிறோம். ஆரோக்கியமான சாப்பாடு எளிதாகவும் வசதியாகவும் செய்யப்பட்டுள்ளது.',
        'footer.categories': 'வகைகள்',
        'footer.quick_links': 'விரைவான அணுகல்',
        'footer.contact_us': 'தொடர்பு கொள்ளுங்கள்',
        'footer.phone': '+91 7200558060 / +91 9994014301',
        'footer.email': 'hello@umade.com',
        'footer.hours': 'திங்கள் - ஞாயிறு: காலை 7:00 - இரவு 10:00',
        'footer.copyright': 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை. ஆரோக்கியமான வாழ்க்கைக்காக அன்புடன் உருவாக்கப்பட்டது.',
        'footer.privacy': 'தனியுரிமைக் கொள்கை',
        'footer.terms': 'சேவை விதிமுறைகள்',
        'footer.cookies': 'குக்கீ கொள்கை',

        // Cart
        'cart.title': 'உங்கள் வண்டி',
        'cart.total': 'மொத்தம்:',
        'cart.checkout': 'செலுத்துங்கள்',
        'cart.clear': 'வண்டியை காலி செய்யுங்கள்',

        // Login
        'login.sign_in': 'உள்நுழையுங்கள்',
        'login.welcome_back': 'மீண்டும் வரவேற்கிறோம்! உங்கள் விவரங்களை உள்ளிடவும்.',
        'login.email': 'மின்னஞ்சல் முகவரி',
        'login.password': 'கடவுச்சொல்',
        'login.remember': 'என்னை நினைவில் கொள்ளுங்கள்',
        'login.forgot': 'கடவுச்சொல் மறந்துவிட்டதா?',
        'login.or_continue': 'அல்லது தொடரவும்',
        'login.google': 'கூகுள்',
        'login.apple': 'ஆப்பிள்',
        'login.no_account': 'கணக்கு இல்லையா?',
        'login.sign_up': 'பதிவு செய்யுங்கள்',
        'login.first_name': 'முதல் பெயர்',
        'login.last_name': 'கடைசி பெயர்',
        'login.phone': 'தொலைபேசி எண்',
        'login.confirm_password': 'கடவுச்சொலை உறுதிப்படுத்தவும்',
        'login.agree': 'விதிமுறைகள் மற்றும் தனியுரிமைக் கொள்கையை ஏற்கிறேன்',
        'login.create_account': 'கணக்கை உருவாக்குங்கள்',
        'login.have_account': 'ஏற்கனவே கணக்கு உள்ளதா?',
        'login.reset': 'கடவுச்சொல்லை மீட்டமைக்கவும்',
        'login.reset_desc': 'உங்கள் மின்னஞ்சலை உள்ளிடவும், மீட்டமைப்பு இணைப்பை அனுப்புவோம்.',
        'login.send_link': 'மீட்டமைப்பு இணைப்பை அனுப்புங்கள்',

        // Tracking
        'tracking.live_tracking': 'நேரடி ஆர்டர் கண்காணிப்பு',
        'tracking.title': 'உங்கள் ஆர்டர் வழியில் உள்ளது',
        'tracking.subtitle': 'எங்கள் பண்ணையிலிருந்து உங்கள் வீட்டு வாசலுக்கு நேரடியாக உங்கள் கரிம மளிகைப் பொருட்களைக் கண்காணிக்கவும்.',
        'tracking.order_number': 'ஆர்டர் எண்',
        'tracking.order_date': 'ஆர்டர் தேதி',
        'tracking.items': 'பொருட்கள்',
        'tracking.total': 'மொத்தம்',
        'tracking.live': 'நேரடி',
        'tracking.distance': 'தூரம்',
        'tracking.time': 'நிமிடம்',
        'tracking.speed': 'கி.மீ/மணி',
        'tracking.call': 'அழைக்கவும்',
        'tracking.message': 'செய்தி',
        'tracking.progress': 'விநியோக முன்னேற்றம்',
        'tracking.placed': 'ஆர்டர் வைக்கப்பட்டது',
        'tracking.preparing': 'தயாரிப்பு',
        'tracking.out_delivery': 'விநியோகத்திற்கு வெளியே',
        'tracking.on_way': 'வழியில்',
        'tracking.arriving': 'வருகிறது',
        'tracking.delivered': 'வழங்கப்பட்டது',
        'tracking.estimated': 'மதிப்பிடப்பட்டது',
        'tracking.order_items': 'ஆர்டர் பொருட்கள்',

        // Loyalty
        'loyalty.title': 'உமேட் வெகுமதிகள்',
        'loyalty.subtitle': 'ஒவ்வொரு கொள்முதலிலும் புள்ளிகளைப் பெற்று தள்ளுபடிக்கு மாற்றுங்கள்',
        'loyalty.points_balance': 'புள்ளி இருப்பு',
        'loyalty.points_earned': 'பெறப்பட்ட புள்ளிகள்',
        'loyalty.points_redeemed': 'மீட்டெடுக்கப்பட்ட புள்ளிகள்',
        'loyalty.tier': 'உறுப்பினர் நிலை',
        'loyalty.gold': 'தங்கம்',
        'loyalty.how_to_earn': 'புள்ளிகளை எவ்வாறு பெறுவது',
        'loyalty.earn_rate': '₹10 செலவுக்கு 1 புள்ளி',
        'loyalty.redeem_rate': '100 புள்ளிகள் = ₹50 தள்ளுபடி',
        'loyalty.purchase_points': 'கொள்முதல் புள்ளிகள்',
        'loyalty.purchase_desc': '₹10 செலவுக்கு 1 புள்ளி பெறுங்கள்',
        'loyalty.review_points': 'மதிப்பீட்டு புள்ளிகள்',
        'loyalty.review_desc': 'ஒவ்வொரு தயாரிப்பு மதிப்பீட்டிற்கும் 50 புள்ளிகள்',
        'loyalty.refer_points': 'பரிந்துரை புள்ளிகள்',
        'loyalty.refer_desc': 'ஒவ்வொரு வெற்றிகரமான பரிந்துரைக்கும் 200 புள்ளிகள்',
        'loyalty.social_points': 'சமூக புள்ளிகள்',
        'loyalty.social_desc': 'சமூக ஊடகங்களில் பகிர்வதற்கு 25 புள்ளிகள்',
        'loyalty.redeem_title': 'உங்கள் புள்ளிகளை மீட்டெடுக்கவும்',
        'loyalty.redeem_100': '₹50 தள்ளுபடி',
        'loyalty.redeem_200': '₹125 தள்ளுபடி',
        'loyalty.redeem_500': '₹350 தள்ளுபடி',
        'loyalty.redeem_1000': '₹800 தள்ளுபடி',
        'loyalty.history': 'புள்ளி வரலாறு',
        'loyalty.date': 'தேதி',
        'loyalty.activity': 'செயல்பாடு',
        'loyalty.points': 'புள்ளிகள்',
        'loyalty.status': 'நிலை',

        // Referral
        'referral.title': 'பரிந்துரை & பெறுங்கள்',
        'referral.subtitle': 'நண்பர்களுடன் உமேட்டைப் பகிர்ந்து வெகுமதிகளைப் பெறுங்கள்',
        'referral.your_code': 'உங்கள் பரிந்துரை குறியீடு',
        'referral.copy': 'நகலெடுக்கவும்',
        'referral.share': 'பகிருங்கள்',
        'referral.whatsapp': 'வாட்ஸ்அப்',
        'referral.sms': 'SMS',
        'referral.email': 'மின்னஞ்சல்',
        'referral.how_it_works': 'இது எப்படி வேலை செய்கிறது',
        'referral.step1': 'உங்கள் தனித்துவமான பரிந்துரை குறியீட்டை நண்பர்களுடன் பகிருங்கள்',
        'referral.step2': 'நண்பர்கள் தங்கள் முதல் ஆர்டரில் ₹100 தள்ளுபடி பெறுகிறார்கள்',
        'referral.step3': 'நீங்கள் ₹100 கடன் + 200 விசுவாச புள்ளிகளைப் பெறுகிறீர்கள்',
        'referral.stats': 'உங்கள் பரிந்துரை புள்ளிவிவரங்கள்',
        'referral.total_referrals': 'மொத்த பரிந்துரைகள்',
        'referral.successful': 'வெற்றிகரமானது',
        'referral.pending': 'நிலுவையில்',
        'referral.earnings': 'மொத்த வருவாய்',
        'referral.friends_title': 'நீங்கள் பரிந்துரைத்த நண்பர்கள்',
        'referral.friend_name': 'நண்பர்',
        'referral.order_value': 'ஆர்டர் மதிப்பு',
        'referral.your_reward': 'உங்கள் வெகுமதி',
        'referral.referral_status': 'நிலை'
    }
};

// Make translations available globally
if (typeof window !== 'undefined') {
    window.translations = translations;
}
